### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by nzfarmer** [ty4tw/MQTT-SN#5]
I'd be very keen to hear from anyone running this in production using XBees.  We have had the gateway working but it is currently stuck on SEARCHGW.   No doubt a local config issue that we're yet to resolve, but I'm a little concerned how easily these seem to creep in and how hard they are to detect.

**Comment by Rob4579** [comment]
>  We have had the gateway working but it is currently stuck on SEARCHGW.

> 

Me and my co-worker are currently on the same issue.  Did you found the source of your problem nzfarmer?

**Comment by khaledbk** [comment]
@ty4tw, Hi we had the same issue is there any solution ?
