### ISSUE TITLE
TomyClient return "argument error"

### ISSUE THREAD

**Issue by thuandt** [ty4tw/MQTT-SN#8]
I run example client with command in the README and got this message. Someone can tell me my what's wrong?

```bash
root@demo:~/dev# ./TomyClient -i ClientID -g 255.1.1.1 -p 1883 -c -t WillTopic -m WillMessage -k 300
Client start
argument error
root@demo:~/dev# 
```

**Comment by shravan1992** [comment]
Iam also not getting this one can you please help for this error
thank you
