### ISSUE TITLE
Need help about your code

### ISSUE THREAD

**Issue by bevinhex** [ty4tw/MQTT-SN#9]
Hi, I'd like to know if the project is still under development, if yes, what is the final result you expect?
Because I got have the feeling that, we could turn the project into something bridges sensor network with mqtt broker(mosquitto) , not only xbee, but others. I think we should change the building process, so that it can be built and installed as *NIX server on background. We can even upload it into standard Linux repository, so that everyone can install by only command line "apt-get / yum ... "
What do you think?

**Comment by ty4tw** [comment]
No problem
